#!/bin/bash

gulp
cp dist/css/sb-admin-2.css ../testeTemplate/public/dist/css/sb-admin-2.css
cp dist/css/sb-admin-2.min.css ../testeTemplate/public/dist/css/sb-admin-2.min.css

cp js/standalone/selectize.min.js ../testeTemplate/public/dist/js/selectize.min.js
cp dist/css/selectize.default.css ../testeTemplate/public/dist/css/selectize.default.css
